name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GENERATE_SOURCEMAP: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          architecture: "x64"

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

  publish_swarm:
    name: Publish on Swarm
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: build-artifacts-${{ github.sha }}

      - name: Upload to swarm
        uses: Etherna/swarm-upload-action@2.0.0
        with:
          gateway: https://gateway.etherna.io
          localRoot: dist
          defaultPath: index.html
          errorPath: index.html
          ethernaApiKey: ${{ secrets.ETHERNA_API_KEY }}
          batchId: ${{ secrets.BATCH_ID }}
          feedName: SwarmFeedResolver
